from ExploreData.widgets import (
    build_globe_plot,
)
from Timeline.timeline import build_scroll_timeline_section
from Timeline.weight_histogram import build_weight_histogram_plot
from Timeline.impacts_per_year import build_impacts_per_year_plot
from Timeline.meteorite_classes_barchart import build_meteorite_classes_barchart_plot
from Introduction.meteorite_introduction import build_meteor_introduction
from ExploreData.formatting import format_mass
from ExploreData.filters import filter_and_sample
__requires__ = ["pandas", "plotly", "scipy"]
import pandas as pd
import numpy as np
import sys
from pathlib import Path
from shiny import App, render, ui, reactive
from shinywidgets import output_widget, render_widget
sys.path.insert(0, str(Path(__file__).parent))

# Load cleaned data generated by data/data.py
def load_cleaned_data():
    data_rel_path = Path("data/processed/Meteorite_Landings_cleaned.csv")
    candidate_paths = [
        Path(__file__).parent / data_rel_path,
        Path(__file__).parent.parent / data_rel_path,
    ]
    for data_path in candidate_paths:
        try:
            df = pd.read_csv(data_path)
            df["log_mass"] = np.log10(df["mass_g"])
            return df
        except Exception:
            continue
    print(f"Error: could not load cleaned data from any of {candidate_paths}")
    return pd.DataFrame()


meteorites = load_cleaned_data()

if meteorites.empty:
    MASS_LOG_MIN = -2.0
    MASS_LOG_MAX = 8.0
else:
    MASS_LOG_MIN = float(np.floor(meteorites["log_mass"].min() * 10) / 10)
    MASS_LOG_MAX = float(np.ceil(meteorites["log_mass"].max() * 10) / 10)


def tooltip_label(label, tooltip_text):
    return ui.span(
        label,
        ui.span(
            ui.tags.span(
                "i",
                class_="tooltip-icon",
                tabindex="0",
                role="button",
                **{"aria-label": f"Information about {label}"},
            ),
            ui.tags.span(tooltip_text, class_="menu-tooltip", role="tooltip"),
            class_="tooltip-wrap",
        ),
        class_="label-with-tooltip",
    )


app_ui = ui.page_fluid(
    ui.tags.head(
        ui.tags.link(
            rel="stylesheet", href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"),
        ui.tags.style("""
            body { background-color: #121212; color: #e0e0e0; margin: 0; padding: 0; }
            .container-fluid { padding: 0 !important; }
            
            .menu-widget {
                position: sticky;
                top: 24px;
                width: 320px;
                max-height: calc(100vh - 48px);
                background: #2a2a2a;
                border: 1px solid rgba(255, 255, 255, 0.15);
                border-radius: 12px;
                padding: 20px;
                box-shadow: 0 15px 50px rgba(0, 0, 0, 0.9);
                overflow-y: auto;
            }

            .site-nav {
                position: fixed;
                top: 14px;
                right: 18px;
                display: flex;
                gap: 8px;
                z-index: 5000;
            }

            .site-nav-link {
                display: inline-block;
                padding: 6px 12px;
                border-radius: 999px;
                border: 1px solid rgba(138, 180, 248, 0.35);
                background: rgba(24, 24, 24, 0.9);
                color: #cddfff;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 0.02em;
                text-decoration: none;
                transition: background-color 160ms ease, border-color 160ms ease, color 160ms ease;
            }

            .site-nav-link:hover {
                color: #ffffff;
                border-color: rgba(138, 180, 248, 0.7);
                background: rgba(40, 57, 84, 0.95);
            }

            .globe-section {
                background-color: #1f1f1f;
                overflow: hidden;
                padding: 150px 24px 24px;
            }

            .insight-section {
                --timeline-max-width: 1120px;
                background-color: #1f1f1f;
                padding: 36px 24px 60px;
            }

            .insight-section.spacer-after-globe {
                padding-top: 300px;
            }

            .insight-section.spacer-before-barchart {
                padding-top: 300px;
            }

            .insight-section.spacer-before-impacts {
                padding-top: 300px;
            }

            .insight-section .timeline-header {
                max-width: var(--timeline-max-width);
                margin: 0 auto 22px auto;
            }

            .insight-plot-wrap {
                max-width: var(--timeline-max-width);
                margin: 0 auto;
                border-radius: 14px;
                border: 1px solid rgba(255, 255, 255, 0.09);
                background: rgba(18, 18, 18, 0.55);
                box-shadow: 0 12px 26px rgba(0, 0, 0, 0.45);
                padding: 12px 12px 2px;
            }

            .globe-layout {
                max-width: none;
                margin: 0;
                width: 100%;
                display: flex;
                gap: 16px;
                align-items: flex-start;
            }

            .globe-plot-wrap {
                flex: 1;
                min-width: 0;
            }
            
            .chart-card {
                background: #1f1f1f; border-radius: 16px;
                border: 1px solid rgba(255, 255, 255, 0.1);
                padding: 20px; margin-bottom: 30px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            }

            .globe-title-section {
                --timeline-max-width: 1120px;
                padding: 64px 24px 0;
                background-color: #1f1f1f;
            }

            .globe-title-section .timeline-header {
                margin-bottom: 0;
            }
            
            .irs-grid-text { color: #777 !important; }
            .irs-single, .irs-from, .irs-to { background: #0d6efd !important; border-color: #0a58ca !important; }
            .irs-bar { background: #0d6efd !important; border-top: 1px solid #0d6efd !important; border-bottom: 1px solid #0d6efd !important; }
            .irs-handle { border: 1px solid #0d6efd !important; background: #0d6efd !important; }
            
            label { font-weight: 600; color: #999 !important; text-transform: uppercase; font-size: 11px; letter-spacing: 1.5px; margin-bottom: 10px; }
            
            h3 { font-weight: 800; color: #fff; letter-spacing: -0.5px; margin-top: 0; }
            .impact-count { font-size: 14px; color: #00ff00 !important; font-family: monospace; font-weight: bold; }

            .label-with-tooltip {
                display: inline-flex;
                align-items: center;
                gap: 6px;
                position: relative;
            }

            .tooltip-wrap {
                display: inline-flex;
                align-items: center;
                position: relative;
                letter-spacing: normal;
                text-transform: none;
            }

            .tooltip-icon {
                display: inline-flex;
                align-items: center;
                justify-content: center;
                width: 16px;
                height: 16px;
                border-radius: 999px;
                background: #0d6efd;
                color: #fff;
                cursor: help;
                font-size: 11px;
                font-weight: 800;
                line-height: 1;
                letter-spacing: normal;
                text-transform: none;
                user-select: none;
            }

            .tooltip-icon:focus {
                outline: 2px solid rgba(13, 110, 253, 0.45);
                outline-offset: 2px;
            }

            .menu-tooltip {
                position: absolute;
                bottom: calc(100% + 8px);
                left: 50%;
                z-index: 10000;
                width: max-content;
                max-width: 220px;
                padding: 8px 10px;
                border-radius: 8px;
                background: #0d6efd;
                box-shadow: 0 8px 22px rgba(0, 0, 0, 0.35);
                color: #fff;
                font-size: 11px;
                font-weight: 500;
                line-height: 1.35;
                letter-spacing: normal;
                text-align: left;
                text-transform: none;
                transform: translateX(-50%);
                opacity: 0;
                pointer-events: none;
                visibility: hidden;
                transition: opacity 140ms ease, visibility 140ms ease;
            }

            .menu-tooltip::after {
                content: "";
                position: absolute;
                top: 100%;
                left: 50%;
                transform: translateX(-50%);
                border: 6px solid transparent;
                border-top-color: #0d6efd;
            }

            .tooltip-wrap:hover .menu-tooltip,
            .tooltip-wrap:focus-within .menu-tooltip {
                opacity: 1;
                visibility: visible;
            }
            
            /* Toggle Switch Labels */
            .form-check-label { color: #bbb !important; font-size: 12px; font-weight: 500; }

            @media (max-width: 980px) {
                .globe-layout {
                    flex-direction: column;
                }

                .menu-widget {
                    position: relative;
                    top: 0;
                    width: 100%;
                    max-height: none;
                }
            }

            .app-footer {
                text-align: center;
                padding: 20px 24px 28px;
                color: #9a9a9a;
                font-size: 13px;
                background-color: #121212;
            }

            .app-footer a {
                color: #8ab4f8;
                text-decoration: none;
            }

            .app-footer a:hover {
                text-decoration: underline;
            }
        """),
        ui.tags.script("""
            document.addEventListener("click", function(event) {
                const trigger = event.target.closest(".tooltip-icon");
                if (!trigger) return;
                event.preventDefault();
                event.stopPropagation();
                trigger.focus();
            }, true);
        """)
    ),

    ui.div(
        ui.tags.a("Docs", href="../docs/", target="_top", class_="site-nav-link"),
        ui.tags.a("Presentation", href="../presentation/", target="_top", class_="site-nav-link"),
        class_="site-nav",
    ),

    build_meteor_introduction(),

    build_scroll_timeline_section(),

    ui.div(
        ui.div(
            ui.tags.p("Interactive Globe", class_="timeline-kicker"),
            ui.tags.h2("Explore the whole dataset of Impacts",
                       class_="timeline-heading"),
            ui.tags.p(
                "Change settings in the Menu and Drag the Globe",
                class_="timeline-subtitle",
            ),
            class_="timeline-header",
        ),
        class_="globe-title-section",
    ),

    # Globe Section
    ui.div(
        ui.div(
            ui.output_ui("menu_container"),
            ui.div(
                output_widget("globe_plot", height="70vh", width="100%"),
                class_="globe-plot-wrap",
            ),
            class_="globe-layout",
        ),
        class_="globe-section",
    ),

    ui.div(
        ui.div(
            ui.tags.p("Distribution", class_="timeline-kicker"),
            ui.tags.h2("Weight Histogram", class_="timeline-heading"),
            ui.tags.p(
                "Zoom in with your Fingers, Reset by pressing the House",
                class_="timeline-subtitle",
            ),
            class_="timeline-header",
        ),
        ui.div(
            output_widget("weight_histogram_plot", height="56vh", width="100%"),
            class_="insight-plot-wrap",
        ),
        class_="insight-section spacer-after-globe",
    ),

    ui.div(
        ui.div(
            ui.tags.p("Trend", class_="timeline-kicker"),
            ui.tags.h2("Impacts per Year", class_="timeline-heading"),
            ui.tags.p(
                "Yearly impact counts split by Found (red) and Fallen (blue).",
                class_="timeline-subtitle",
            ),
            class_="timeline-header",
        ),
        ui.div(
            output_widget("impacts_per_year_plot", height="56vh", width="100%"),
            class_="insight-plot-wrap",
        ),
        class_="insight-section spacer-before-impacts",
    ),

    ui.div(
        ui.div(
            ui.tags.p("Composition", class_="timeline-kicker"),
            ui.tags.h2("Barchart of Meteorite Classes",
                       class_="timeline-heading"),
            ui.tags.p(
                "Top 5 most common meteorite classes in the dataset.",
                class_="timeline-subtitle",
            ),
            class_="timeline-header",
        ),
        ui.div(
            output_widget("meteorite_classes_barchart_plot",
                          height="56vh", width="100%"),
            class_="insight-plot-wrap",
        ),
        class_="insight-section spacer-before-barchart",
    ),

    ui.div(
        ui.tags.span("Dataset source: "),
        ui.tags.a(
            "NASA Open Data - Meteorite Landings",
            href="https://data.nasa.gov/dataset/meteorite-landings",
            target="_blank",
            rel="noopener noreferrer",
        ),
        class_="app-footer",
    )
)


def server(input, output, session):
    # Defaults
    cur_years = reactive.Value([1950, 2024])
    cur_mass_log = reactive.Value([MASS_LOG_MIN, MASS_LOG_MAX])
    cur_limit = reactive.Value(1000)
    cur_fall_filter = reactive.Value(["Fell", "Found"])
    cur_sampling_mode = reactive.Value("hybrid")

    # Trace Toggles
    show_impacts = reactive.Value(True)
    show_heatmap = reactive.Value(False)

    @reactive.calc
    def filtered_data():
        if meteorites.empty:
            return pd.DataFrame()
        try:
            years = input.year_range()
            mass_log = input.mass_range_log()
            limit = input.limit()
            fall_types = input.fall_filter()
            sampling_mode = input.sampling_mode()
        except (TypeError, ValueError, RuntimeError):
            years = cur_years()
            mass_log = cur_mass_log()
            limit = cur_limit()
            fall_types = cur_fall_filter()
            sampling_mode = cur_sampling_mode()
        return filter_and_sample(
            meteorites,
            years=years,
            mass_log=mass_log,
            fall_types=fall_types,
            limit=limit,
            sampling_mode=sampling_mode,
            seed=42,
        )

    @output
    @render.ui
    def menu_container():
        return ui.div(
            ui.h3("IMPACT DATA"),
            ui.div(ui.output_text("count_summary"), class_="impact-count"),
            ui.hr(style="border-color: #333; margin: 15px 0;"),
            ui.input_switch("show_impacts", "Show Impacts",
                            value=show_impacts()),
            ui.input_switch("show_heatmap", tooltip_label(
                "Show 3D Heatmap",
                "A heatmap uses color intensity to show where meteorite impacts are most concentrated.",
            ),
                            value=show_heatmap()),
            ui.hr(style="border-color: #333; margin: 15px 0;"),
            ui.input_checkbox_group(
                "fall_filter",
                tooltip_label(
                    "FALL TYPE",
                    "Fall = observed falling meteorite; Found = discovered after impact.",
                ),
                {"Fell": "Fallen", "Found": "Found"},
                selected=cur_fall_filter(),
                inline=True
            ),
            ui.input_slider("year_range", "YEARS",
                            min=int(meteorites['year'].min()),
                            max=int(meteorites['year'].max()),
                            value=cur_years(),
                            sep=""),
            ui.input_slider("mass_range_log", "MASS (log)",
                            min=MASS_LOG_MIN, max=MASS_LOG_MAX, value=cur_mass_log(), step=0.1),
            ui.div(ui.output_text("mass_range_label"),
                   style="font-size: 12px; color: #bbb; margin-top: 6px;"),
            ui.input_select(
                "sampling_mode", "SAMPLING MODE",
                {
                    "hybrid": "Hybrid (recommended)",
                    "random": "Random",
                    "top_mass": "Top mass"
                },
                selected=cur_sampling_mode()
            ),
            ui.input_numeric("limit", "MAX POINTS",
                             value=cur_limit(), min=1, max=45000),
            class_="menu-widget"
        )

    @render.text
    def count_summary():
        df = filtered_data()
        return f"{len(df):,} DETECTED IMPACTS"

    @render.text
    def mass_range_label():
        try:
            mass_log = input.mass_range_log()
        except (TypeError, ValueError, RuntimeError):
            mass_log = cur_mass_log()
        low_g = 10 ** mass_log[0]
        high_g = 10 ** mass_log[1]
        return f"Selected mass: {format_mass(low_g)} to {format_mass(high_g)}"

    @render_widget
    def globe_plot():
        df = filtered_data()
        try:
            s_heatmap = input.show_heatmap()
        except (TypeError, ValueError, RuntimeError):
            s_heatmap = show_heatmap()
        try:
            s_impacts = input.show_impacts()
        except (TypeError, ValueError, RuntimeError):
            s_impacts = show_impacts()
        try:
            mass_log = input.mass_range_log()
        except (TypeError, ValueError, RuntimeError):
            mass_log = cur_mass_log()
        return build_globe_plot(
            df,
            mass_log=mass_log,
            show_impacts=s_impacts,
            show_heatmap=s_heatmap,
        )

    @render_widget
    def weight_histogram_plot():
        return build_weight_histogram_plot(meteorites)

    @render_widget
    def impacts_per_year_plot():
        return build_impacts_per_year_plot(meteorites)

    @render_widget
    def meteorite_classes_barchart_plot():
        return build_meteorite_classes_barchart_plot(meteorites)


app = App(app_ui, server)
