from ExploreData.widgets import (
    build_class_bar,
    build_globe_plot,
    build_heatmap_2d,
    build_mass_hist,
    build_timeline_plot,
)
from Timeline.timeline import build_scroll_timeline_section
from Introduction.meteorite_introduction import build_meteor_introduction
from ExploreData.formatting import format_mass
from ExploreData.filters import filter_and_sample
__requires__ = ["pandas", "plotly", "scipy"]
import pandas as pd
import numpy as np
import sys
from pathlib import Path
from shiny import App, render, ui, reactive
from shinywidgets import output_widget, render_widget
sys.path.insert(0, str(Path(__file__).parent))


# Load cleaned data generated by data/data.py
def load_cleaned_data():
    data_rel_path = Path("data/processed/Meteorite_Landings_cleaned.csv")
    candidate_paths = [
        Path(__file__).parent / data_rel_path,
        Path(__file__).parent.parent / data_rel_path,
    ]
    for data_path in candidate_paths:
        try:
            df = pd.read_csv(data_path)
            df["log_mass"] = np.log10(df["mass_g"])
            return df
        except Exception:
            continue
    print(f"Error: could not load cleaned data from any of {candidate_paths}")
    return pd.DataFrame()


meteorites = load_cleaned_data()

if meteorites.empty:
    MASS_LOG_MIN = -2.0
    MASS_LOG_MAX = 8.0
else:
    MASS_LOG_MIN = float(np.floor(meteorites["log_mass"].min() * 10) / 10)
    MASS_LOG_MAX = float(np.ceil(meteorites["log_mass"].max() * 10) / 10)

app_ui = ui.page_fluid(
    ui.tags.head(
        ui.tags.link(
            rel="stylesheet", href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"),
        ui.tags.style("""
            body { background-color: #121212; color: #e0e0e0; margin: 0; padding: 0; }
            .container-fluid { padding: 0 !important; }
            
            .menu-widget {
                position: sticky;
                top: 24px;
                width: 320px;
                max-height: calc(100vh - 48px);
                background: #2a2a2a;
                border: 1px solid rgba(255, 255, 255, 0.15);
                border-radius: 12px;
                padding: 20px;
                box-shadow: 0 15px 50px rgba(0, 0, 0, 0.9);
                overflow-y: auto;
            }

            .globe-section {
                background-color: #1f1f1f;
                overflow: hidden;
                padding: 150px 24px 24px;
            }

            .globe-layout {
                max-width: 1120px;
                margin: 0 auto;
                display: flex;
                gap: 24px;
                align-items: flex-start;
            }

            .globe-plot-wrap {
                flex: 1;
                min-width: 0;
            }
            
            .chart-card {
                background: #1f1f1f; border-radius: 16px;
                border: 1px solid rgba(255, 255, 255, 0.1);
                padding: 20px; margin-bottom: 30px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            }

            .globe-title-section {
                --timeline-max-width: 1120px;
                padding: 64px 24px 0;
                background-color: #1f1f1f;
            }

            .globe-title-section .timeline-header {
                margin-bottom: 0;
            }
            
            .irs-grid-text { color: #777 !important; }
            .irs-single, .irs-from, .irs-to { background: #0d6efd !important; border-color: #0a58ca !important; }
            .irs-bar { background: #0d6efd !important; border-top: 1px solid #0d6efd !important; border-bottom: 1px solid #0d6efd !important; }
            .irs-handle { border: 1px solid #0d6efd !important; background: #0d6efd !important; }
            
            label { font-weight: 600; color: #999 !important; text-transform: uppercase; font-size: 11px; letter-spacing: 1.5px; margin-bottom: 10px; }
            
            h3 { font-weight: 800; color: #fff; letter-spacing: -0.5px; margin-top: 0; }
            .impact-count { font-size: 14px; color: #00ff00 !important; font-family: monospace; font-weight: bold; }
            
            /* Toggle Switch Labels */
            .form-check-label { color: #bbb !important; font-size: 12px; font-weight: 500; }

            @media (max-width: 980px) {
                .globe-layout {
                    flex-direction: column;
                }

                .menu-widget {
                    position: relative;
                    top: 0;
                    width: 100%;
                    max-height: none;
                }
            }
        """)
    ),

    build_meteor_introduction(),

    build_scroll_timeline_section(),

    ui.div(
        ui.div(
            ui.tags.p("Interactive Globe", class_="timeline-kicker"),
            ui.tags.h2("Explore the whole dataset of Impacts",
                       class_="timeline-heading"),
            ui.tags.p(
                "Change settings in the Menu",
                class_="timeline-subtitle",
            ),
            class_="timeline-header",
        ),
        class_="globe-title-section",
    ),

    # Globe Section
    ui.div(
        ui.div(
            ui.output_ui("menu_container"),
            ui.div(
                output_widget("globe_plot", height="70vh", width="100%"),
                class_="globe-plot-wrap",
            ),
            class_="globe-layout",
        ),
        class_="globe-section",
    ),

    """
    # Widget Section
    ui.div(
        ui.row(
            ui.column(8,
                      ui.div(
                          ui.h4("GLOBAL DISTRIBUTION HEATMAP",
                                style="margin-bottom: 20px; color: #666; font-size: 12px; font-weight: 900;"),
                          output_widget("heatmap_2d", height="400px"),
                          class_="chart-card"
                      ),
                      ),
            ui.column(4,
                      ui.div(
                          ui.h4(
                              "IMPACTS PER YEAR", style="margin-bottom: 20px; color: #666; font-size: 12px; font-weight: 900;"),
                          output_widget("timeline_plot", height="400px"),
                          class_="chart-card"
                      )
                      ),
            style="padding: 30px 30px 0 30px;"
        ),
        ui.row(
            ui.column(6,
                      ui.div(
                          ui.h4("MASS DISTRIBUTION (LOG SCALE)",
                                style="margin-bottom: 20px; color: #666; font-size: 12px; font-weight: 900;"),
                          output_widget("mass_hist", height="400px"),
                          class_="chart-card"
                      ),
                      ),
            ui.column(6,
                      ui.div(
                          ui.h4("TOP 10 METEORITE CLASSES",
                                style="margin-bottom: 20px; color: #666; font-size: 12px; font-weight: 900;"),
                          output_widget("class_bar", height="400px"),
                          class_="chart-card"
                      )
                      ),
            style="padding: 0 30px 30px 30px;"
        ),
        style="position: relative; z-index: 10; background-color: #121212;"
    ),
    """,
)


def server(input, output, session):
    # Defaults
    cur_years = reactive.Value([1950, 2024])
    cur_mass_log = reactive.Value([MASS_LOG_MIN, MASS_LOG_MAX])
    cur_limit = reactive.Value(1000)
    cur_fall_filter = reactive.Value(["Fell", "Found"])
    cur_sampling_mode = reactive.Value("hybrid")

    # Trace Toggles
    show_impacts = reactive.Value(True)
    show_heatmap = reactive.Value(False)

    @reactive.calc
    def filtered_data():
        if meteorites.empty:
            return pd.DataFrame()
        try:
            years = input.year_range()
            mass_log = input.mass_range_log()
            limit = input.limit()
            fall_types = input.fall_filter()
            sampling_mode = input.sampling_mode()
        except (TypeError, ValueError, RuntimeError):
            years = cur_years()
            mass_log = cur_mass_log()
            limit = cur_limit()
            fall_types = cur_fall_filter()
            sampling_mode = cur_sampling_mode()
        return filter_and_sample(
            meteorites,
            years=years,
            mass_log=mass_log,
            fall_types=fall_types,
            limit=limit,
            sampling_mode=sampling_mode,
            seed=42,
        )

    @output
    @render.ui
    def menu_container():
        return ui.div(
            ui.h3("ORBITAL DATA"),
            ui.div(ui.output_text("count_summary"), class_="impact-count"),
            ui.hr(style="border-color: #333; margin: 15px 0;"),
            ui.input_switch("show_impacts", "Show Impacts",
                            value=show_impacts()),
            ui.input_switch("show_heatmap", "Show 3D Heatmap",
                            value=show_heatmap()),
            ui.hr(style="border-color: #333; margin: 15px 0;"),
            ui.input_checkbox_group(
                "fall_filter", "FALL TYPE",
                {"Fell": "Fallen", "Found": "Found"},
                selected=cur_fall_filter(),
                inline=True
            ),
            ui.input_slider("year_range", "YEARS",
                            min=int(meteorites['year'].min()),
                            max=int(meteorites['year'].max()),
                            value=cur_years(),
                            sep=""),
            ui.input_slider("mass_range_log", "MASS (log)",
                            min=MASS_LOG_MIN, max=MASS_LOG_MAX, value=cur_mass_log(), step=0.1),
            ui.div(ui.output_text("mass_range_label"),
                   style="font-size: 12px; color: #bbb; margin-top: 6px;"),
            ui.input_select(
                "sampling_mode", "SAMPLING MODE",
                {
                    "hybrid": "Hybrid (recommended)",
                    "random": "Random",
                    "top_mass": "Top mass"
                },
                selected=cur_sampling_mode()
            ),
            ui.input_numeric("limit", "MAX POINTS",
                             value=cur_limit(), min=1, max=45000),
            class_="menu-widget"
        )

    @render.text
    def count_summary():
        df = filtered_data()
        return f"{len(df):,} DETECTED IMPACTS"

    @render.text
    def mass_range_label():
        try:
            mass_log = input.mass_range_log()
        except (TypeError, ValueError, RuntimeError):
            mass_log = cur_mass_log()
        low_g = 10 ** mass_log[0]
        high_g = 10 ** mass_log[1]
        return f"Selected mass: {format_mass(low_g)} to {format_mass(high_g)}"

    @render_widget
    def globe_plot():
        df = filtered_data()
        try:
            s_heatmap = input.show_heatmap()
        except (TypeError, ValueError, RuntimeError):
            s_heatmap = show_heatmap()
        try:
            s_impacts = input.show_impacts()
        except (TypeError, ValueError, RuntimeError):
            s_impacts = show_impacts()
        try:
            mass_log = input.mass_range_log()
        except (TypeError, ValueError, RuntimeError):
            mass_log = cur_mass_log()
        return build_globe_plot(
            df,
            mass_log=mass_log,
            show_impacts=s_impacts,
            show_heatmap=s_heatmap,
        )

    @render_widget
    def heatmap_2d():
        df = filtered_data()
        return build_heatmap_2d(df)

    @render_widget
    def timeline_plot():
        df = filtered_data()
        return build_timeline_plot(df)

    @render_widget
    def mass_hist():
        df = filtered_data()
        return build_mass_hist(df)

    @render_widget
    def class_bar():
        df = filtered_data()
        return build_class_bar(df)


app = App(app_ui, server)
