project:
  type: website
  output-dir: build

lang: en
language:
  section-title-appendices: "Appendix"

website:
  sidebar:
    style: "floating"
    collapse-level: 1
    pinned: false
    contents:
      - index.qmd
      - project_charta.qmd
      - data_report.qmd
      - viz_design_report.qmd
      - evaluation.qmd
      - meeting_notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      body-width: 1400px
      

number-sections: true

bibliography: refs.bib
csl: vancouver-brackets.csl

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true